config/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import include, path
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django_pydenticon.views import image as pydenticon_image

# from django.shortcuts import render

# @login_required
# def root(request):
#     return render(request, "root.html")

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("identicon/image/<path:data>/", pydenticon_image, name="pydenticon_image"),
    path("", include("instagram.urls")),
    # path(
    #     "", login_required(TemplateView.as_view(template_name="root.html")), name="root"
    # ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram/urls.py
from django.urls import path, re_path

from . import views

app_name = "instagram"

urlpatterns = [
    path("", views.index, name="index"),
    path("post/new/", views.post_new, name="post_new"),
    path("post/<int:pk>/", views.post_detail, name="post_detail"),
    path("post/<int:pk>/like", views.post_like, name="post_like"),
    path("post/<int:pk>/unlike", views.post_unlike, name="post_unlike"),
    path("post/<int:post_pk>/comment/new/", views.comment_new, name="comment_new"),
    re_path(r"^(?P<username>[\w.@+-]+)/$", views.user_page, name="user_page",),
]

instagram/models.py
import re

from django.db import models
from django.urls import reverse

# from accounts.models import User
# from django.conf import settings
from config.settings.common import AUTH_USER_MODEL


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


# user
# -> Post.objects.filter(author=user)
# -> user.post_set.all()
class Post(BaseModel):
    author = models.ForeignKey(
        AUTH_USER_MODEL, related_name="my_post_set", on_delete=models.CASCADE
    )
    photo = models.ImageField(upload_to="instagram/post/%Y/%m/%d",)
    caption = models.TextField()
    tag_set = models.ManyToManyField("Tag", blank=True)
    location = models.CharField(max_length=100)
    like_user_set = models.ManyToManyField(
        AUTH_USER_MODEL, blank=True, related_name="like_post_set"
    )

    def __str__(self):
        return self.caption

    def extract_tag_list(self):
        # #문자 뒤의 숫자,문자를 긁어오는 정규식
        tag_name_list = re.findall(r"#([a-zA-Z\dㄱ-힣]+)", self.caption)
        tag_list = []
        for tag_name in tag_name_list:
            tag, _ = Tag.objects.get_or_create(name=tag_name)
            tag_list.append(tag)
        return tag_list

    def get_absolute_url(self):
        return reverse("instagram:post_detail", args=[self.pk])

    def is_like_user(self, user):
        return self.like_user_set.filter(pk=user.pk).exists()

    class Meta:
        ordering = ["-id"]


class Comment(BaseModel):
    author = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()

    def __str__(self):
        return self.message

    class Meta:
        ordering = ["-id"]


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


# class LikeUser(models.Model):
#     post = models.ForeignKey(Post, on_delete=models.CASCADE)
#     user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)

instagram/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            "photo",
            "caption",
            "location",
        ]

        # Model이 CharField 일경우 TextArea로 변경할수 있다.
        # widgets = {"caption": forms.Textarea,}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "message",
        ]

instagram/views.py
from datetime import timedelta

from appdirs import user_cache_dir
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from .forms import CommentForm, PostForm
from .models import Post, Comment


@login_required
def index(request):
    timesince = timezone.now() - timedelta(days=3)
    post_list = (
        Post.objects.all()
        .filter(Q(author=request.user) | Q(author__in=request.user.follower_set.all()))
        .filter(created_at__gte=timesince)
    )  # less than equal = lte, greater than equal = gte

    suggested_user_list = (
        get_user_model()
        .objects.all()
        .exclude(pk=request.user.pk)
        .exclude(pk__in=request.user.follower_set.all())[:3]
    )

    comment_form = CommentForm()

    return render(
        request,
        "instagram/index.html",
        {
            "post_list": post_list,
            "suggested_user_list": suggested_user_list,
            "comment_form": comment_form,
        },
    )


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            # post tag를 저장하기 위해 post pk 가 필요하기때문에 저장을 먼저 한다.
            # ManyToMany
            post.save()

            post.tag_set.add(*post.extract_tag_list())
            messages.success(request, "포스팅을 저장했습니다.")
            return redirect(post)  # TODO: get_absolute_url 활용
    else:
        form = PostForm()
    return render(request, "instagram/post_form.html", {"form": form})


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    comment_form = CommentForm()

    return render(
        request,
        "instagram/post_detail.html",
        {"post": post, "comment_form": comment_form},
    )


def user_page(request, username):
    page_user = get_object_or_404(get_user_model(), username=username, is_active=True)

    post_list = Post.objects.filter(author=page_user)
    post_list_count = post_list.count()  # 실제 DB에 count 쿼리를 던지게 된다.
    # len(post_list) # post_list를 메모리에 올린 후 메모리에서 갯수를 반환해준다.

    is_follow = False
    # Login 했다면
    if request.user.is_authenticated:
        is_follow = request.user.follower_set.filter(
            pk=page_user.pk
        ).exists()  # User객체, AnonymousUser

    User = get_user_model()
    following = User.objects.filter(follower_set=page_user)

    # print("following: " + following)
    # print("follower: " + request.user.follower_set)

    return render(
        request,
        "instagram/user_page.html",
        {
            "page_user": page_user,
            "post_list": post_list,
            "post_list_count": post_list_count,
            "is_follow": is_follow,
            "following": following,
        },
    )


@login_required
def post_like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.add(request.user)
    messages.success(request, f"{post}를 좋아합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "instagram:index")
    return redirect(redirect_url)


@login_required
def post_unlike(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.like_user_set.remove(request.user)
    messages.success(request, f"{post}를 좋아요를 취소합니다.")
    redirect_url = request.META.get("HTTP_REFERER", "instagram:index")
    return redirect(redirect_url)


@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, id=post_pk)
    if request.method == "POST":
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

            messages.success(request, "댓글을 저장했습니다.")
            redirect_url = request.META.get("HTTP_REFERER", "instagram:index")

            if request.is_ajax():
                return render(request, "instagram/_comment.html", {"comment": comment})
            return redirect(redirect_url)
        else:
            messages.warning(request, "댓글 입력후 등록해주세요.")
            redirect_url = request.META.get("HTTP_REFERER", "instagram:index")
            return redirect(redirect_url)

instagram/templates/instagram/_comment.html
{% load humanize %}

<div class="media mb-3">
    <a href="{% url "instagram:user_page" comment.author.username %}">
        <img src="{{ comment.author.avatar_url }}" alt="avatar" class="mr-3 rounded-circle"
            style="width:32px; height: 32px;" alt="{{comment.author.username}}">
    </a>
    <div class="media-body">
        <a href="{% url "instagram:user_page" comment.author.username %}">
            {{comment.author.username}}
        </a>
        {{comment.message}}
        <small class="text-muted">
            {{comment.created_at|naturaltime}}
        </small>
    </div>
</div>

instagram/templates/instagram/_post_card.html
{% load instagram_tags %}

{% load humanize %}

<div class="card">
    <div class="card-header">
        <img src="{{ post.author.avatar_url }}" alt="avatar" class="mr-2 rounded-circle"
            style="width:32px; height: 32px;" alt="{{post.author.username}}">
        <a href="{% url "instagram:user_page"  post.author.username %}">
            {{ post.author.username }}
        </a>
    </div>
    <div class="card-body">
        <a href="{% url "instagram:post_detail" post.pk %}">
            <img src="{{ post.photo.url }}" alt="{{ post.caption }}" style="width: 100%;">
        </a>
        <div>
            {% if post|is_like_user:user %}
            <a href="{% url "instagram:post_unlike" post.pk %}">
                <svg aria-label="활동 피드" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                    <path
                        d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                    </path>
                </svg>
            </a>
            {% else %}
            <a href="{% url "instagram:post_like" post.pk%}">
                <svg aria-label="활동 피드" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                    <path
                        d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                    </path>
                </svg>
            </a>
            {% endif %}
        </div>

        <div>
            {% for tag in post.tag_set.all  %}
            <span class="badge badge-secondary">#{{tag.name}}</span>
            {% endfor %}
        </div>

        <div>
            <small class="text-muted">
                {{post.created_at|naturaltime}}
            </small>
        </div>
    </div>
    <div class="card-footer">
        <div id="post-{{ post.pk }}-comment-list" class="comment-list">
            {% for comment in post.comment_set.all %}
            {% include "instagram/_comment.html" %}
            {% endfor %}
        </div>
        {% include "instagram/comment_form.html" %}
    </div>
</div>

instagram/templates/instagram/comment_form.html
{% load bootstrap4 %}

<div class="form-group">
    <form id="post-{{ post.pk }}-comment-form" action="{% url "instagram:comment_new" post.pk%}" method="POST">
        {% csrf_token %}
        <textarea name="message" cols="40" rows="3" class="form-control mb-3" placeholder="댓글을 입력하세요." title=""
            required=""></textarea>
        <input type="submit" class="btn btn-primary float-right" value="댓글 쓰기">
    </form>
</div>

<script>
    $(function() {
        var form_id = "post-{{ post.pk }}-comment-form";
        $("#" + form_id).submit(function(e) {
            e.preventDefault();

            var options = {
                success: function(responseText, statusText, xhr, $form) {
                    $("#post-{{ post.pk }}-comment-list").prepend(responseText)
                }
            };

            $(this).ajaxSubmit(options);
            $("#" + form_id + "> textarea").val("");
        })
    })
</script>

instagram/templates/instagram/index.html
{% extends "instagram/layout.html" %}


{% block content %}
<div class="container">
    <div class="row mb-3">
        <div class="col-sm-12">
            <a href="{% url "instagram:post_new" %}" class="btn btn-primary">새 포스팅 쓰기</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% for post in post_list %}
            <div class="mb-5">
                {% include "instagram/_post_card.html" %}
            </div>
            {% endfor %}
        </div>
        <div class="col-sm-4">
            {% include "instagram/timeline_sidebar.html" %}
        </div>
    </div>
</div>
{% endblock content %}

instagram/templates/instagram/layout.html
{% extends 'layout.html' %}

instagram/templates/instagram/post_detail.html
{% extends "instagram/layout.html" %}

{% load instagram_tags humanize %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-7">
            <figure class="figure">
                <img src="{{post.photo.url}}" class="img-fluid rounded mx-auto d-block" style="width: 100%;"
                    alt="{{post.caption}}">
                <figcaption class="figure-caption">
                    {% for tag in post.tag_set.all  %}
                    <span class="badge badge-secondary">#{{tag.name}}</span>
                    {% endfor %}
                </figcaption>
            </figure>
        </div>
        <div class="col-sm">
            <div class="media">
                <a href="{% url "instagram:user_page" post.author.username %}">
                    <img src="{{ post.author.avatar_url }}" alt="avatar" class="mr-3 rounded-circle"
                        style="width:32px; height: 32px;" alt="{{post.author.username}}">
                </a>
                <div class="media-body">
                    <h5 class="mt-0">
                        <a href="{% url "instagram:user_page" post.author.username %}">
                            {{post.author.username}}
                        </a>
                    </h5>
                    {{post.caption}}
                </div>
            </div>
            <hr />
            <div id="post-{{ post.pk }}-comment-list" class="comment-list">
                {% for comment in post.comment_set.all %}
                {% include "instagram/_comment.html" %}
                {% endfor %}
            </div>
            <hr />
            <div class="media">
                {% if post|is_like_user:user %}
                <a href="{% url "instagram:post_unlike" post.pk %}">
                    <svg aria-label="활동 피드" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                        <path
                            d="M34.6 3.1c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5s1.1-.2 1.6-.5c1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                        </path>
                    </svg>
                </a>
                {% else %}
                <a href="{% url "instagram:post_like" post.pk%}">
                    <svg aria-label="활동 피드" class="_8-yf5 " fill="#262626" height="22" viewBox="0 0 48 48" width="22">
                        <path
                            d="M34.6 6.1c5.7 0 10.4 5.2 10.4 11.5 0 6.8-5.9 11-11.5 16S25 41.3 24 41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3 11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3 1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9 1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9 1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1 0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3 1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3 1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2 7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6 48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                        </path>
                    </svg>
                </a>
                {% endif %}
            </div>
            <hr />

            {% include "instagram/comment_form.html" %}
        </div>
    </div>
</div>
{% endblock content %}

instagram/templates/instagram/post_form.html
{% extends 'instagram/layout.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            {% include "_form.html" with form_title="새 포스트" submit_label="작성완료" %}
        </div>
    </div>
</div>
{% endblock content %}

instagram/templates/instagram/post_list.html
{% extends "instagram/layout.html" %}
{% load bootstrap4 %}

{% block title %}
Instagram / Post List
{% endblock title %}

{% block content %}

{% comment %} <form action="" method="get">
    <input type="text" name="query" value="{{q}}" />
    <input type="submit" value="검색" />
</form> {% endcomment %}

<a href="{% url "instagram:post_new" %}" class="btn btn-primary btn-block mt-3 mb-3">새 포스팅</a>

<table class="table table-bordered table-hover">
    <tbody>
        <thead>
            <tr>
                <th>NO.</th>
                <th>Photo</th>
                <th>Message</th>
                <th>Author</th>
            </tr>
        </thead>
        {% for post in post_list %}
        <tr onClick="location.href='{{ post.get_absolute_url }}'">
            <td>{{ post.id }}</td>
            <td>
                {% if post.photo %}
                <img src={{ post.photo.url }} style="width: 75px;" />
                {% else %}
                No Photo
                {% endif %}
            </td>
            <td>
                {% comment %} <a href="{% url 'instagram:post_detail' post.pk %}"> {% endcomment %}
                    {% comment %} URL Reverse Post Model 참조 {% endcomment %}
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.message }}
                    </a>
                    {% comment %} </a> {% endcomment %}
            </td>
            <td>{{ post.author }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% comment %}
{{ is_paginated }}
{{ page_obj }}
{% endcomment %}
{% comment %} {% if is_paginated %}
{% endif %} {% endcomment %}
{% comment %} {% bootstrap_pagination page_obj size="small" justify_content="center" %} {% endcomment %}

{% endblock content %}

instagram/templates/instagram/timeline_sidebar.html
<div class="d-flex p-2 mb-3">
    <div class="mr-3">
        <img src="{{ user.avatar_url }}" alt="avatar" class="rounded-circle" style="width:48px; height: 48px;" />
    </div>
    <div>
        {{user.username}}<br />
        <small class="text-muted">{{user.name}}</small>
    </div>
</div>

<div class="card mb-3">
    <div class="card-body text-muted">
        <h6 class="card-title">Stories</h6>
        Stories from people you follow will show up here.
    </div>
</div>

<div class="card mb-3">
    <div class="card-body text-muted">
        <div class="row">
            <div class="col-sm-7">
                <h6 class="card-title">Suggestions for you </h6>
            </div>
            <div class="col-sm-5 text-right text-body">
                See All
            </div>
        </div>
        {% for suggested_user in suggested_user_list %}
        {% include 'instagram/timeline_sidebar_user_follow.html'%}
        {% empty %}
        No suggested user
        {% endfor %}
    </div>
</div>

instagram/templates/instagram/timeline_sidebar_user_follow.html
<div class="d-flex mb-2">
    <div class="mr-3"><img src="{{ suggested_user.avatar_url }}" alt="avatar" class="rounded-circle"
            style="width:32px; height: 32px;" /></div>
    <div class="">
        <a href="{% url "instagram:user_page"  suggested_user.username %}">
            {{ suggested_user.username }}
        </a>
    </div>
    <div class="ml-auto"><a href="{% url "user_follow" suggested_user.username %}">Follow</a></div>
    {% comment %} <div class="ml-auto"><a href="{% url "user_unfollow" suggested_user.username %}">Unfollow</a></div>
    {% endcomment %}
</div>

instagram/templates/instagram/user_page.html
{% extends "instagram/layout.html" %}
{% load thumbnail %}


{% block content %}
<div class="container">
    <div class="row pt-5 pb-5">
        <div class="col-sm-3" style="text-align: center;">
            <img src="{{page_user.avatar_url}}" class="rounded-circle" style="width: 200px;"
                alt="{{page_user.username}}">
        </div>
        <div class="col-sm-9">
            {{page_user.username}}
            {% if page_user == user %}
            <a href="{% url "profile_edit" %}">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-tools" fill="currentColor"
                    xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd"
                        d="M0 1l1-1 3.081 2.2a1 1 0 0 1 .419.815v.07a1 1 0 0 0 .293.708L10.5 9.5l.914-.305a1 1 0 0 1 1.023.242l3.356 3.356a1 1 0 0 1 0 1.414l-1.586 1.586a1 1 0 0 1-1.414 0l-3.356-3.356a1 1 0 0 1-.242-1.023L9.5 10.5 3.793 4.793a1 1 0 0 0-.707-.293h-.071a1 1 0 0 1-.814-.419L0 1zm11.354 9.646a.5.5 0 0 0-.708.708l3 3a.5.5 0 0 0 .708-.708l-3-3z" />
                    <path fill-rule="evenodd"
                        d="M15.898 2.223a3.003 3.003 0 0 1-3.679 3.674L5.878 12.15a3 3 0 1 1-2.027-2.027l6.252-6.341A3 3 0 0 1 13.778.1l-2.142 2.142L12 4l1.757.364 2.141-2.141zm-13.37 9.019L3.001 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026z" />
                </svg>
            </a>
            <a href="{%url "logout"%}" class="btn-light btn-sm">로그아웃</a>
            {% elif is_follow == True %}
            <a href="{% url "user_unfollow" page_user.username %}" class="btn btn-light btn-sm">UnFollow</a>
            {% elif is_follow == False%}
            <a href="{% url "user_follow" page_user.username %}" class="btn btn-primary btn-sm">Follow</a>
            {% endif %}
            <hr />
            {{post_list_count}} posts, {{page_user.follower_set.all.count}} followers,
            {{following.count}} followings
            {% comment %}
            <hr />
            {{page_user.follower_set.all}}
            <hr />
            {{following.all}} {% endcomment %}
            <hr />
            {{page_user.name}}
        </div>
    </div>
    <div class="row mt-5">
        {% for post in post_list %}
        <div class="col-sm-3 mb-3">
            <a href="{{ post.get_absolute_url }}">
                <img src="{% thumbnail post.photo 350x350 crop %}" style="width: 100%" alt="{{post.caption}} ">
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}